# Generated by Django 4.2.17 on 2025-01-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_updated_on_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_on"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_on"]},
        ),
    ]
